version: '3.8'

services:
  dashboard:
    build: .
    container_name: sam-dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./.streamlit:/app/.streamlit:ro
    environment:
      - SAM_DATA_DIR=/app/data
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - sam-network

  updater:
    build: .
    container_name: sam-updater
    command: python download_and_update.py
    volumes:
      - ./data:/app/data
    environment:
      - SAM_DATA_DIR=/app/data
      - PYTHONUNBUFFERED=1
    depends_on:
      - dashboard
    networks:
      - sam-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3

networks:
  sam-network:
    driver: bridge

volumes:
  data:
    driver: local